### ISSUE TITLE
Differences to qualification queries in TPC-DS kit templates

### ISSUE THREAD

**Issue by janetzki** [cwida/tpcds-result-reproduction#6]
Hi! The queries for qualification and the answer set in this repository are quite beneficial for us to verify our research database [Hyrise](https://github.com/hyrise/hyrise).
We have noticed that some of the queries have a different form than those that can be generated with the official TPC-DS kit. For example, `query_qualification/39a.sql` includes a factor in the line `stddev_samp(inv_quantity_on_hand)*1.000 stdev,` that is not part of the official query template.
Because we want to benchmark our database as close to the TPC-DS standard as possible, we wanted to ask why these changes were made?
Thank you.

**Comment by hannes** [comment]
Probably because I used an older version of the kit
